# Generated by Django 4.2.7 on 2023-11-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancient_civilizations_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('civilization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancient_civilizations_hub.civilization')),
            ],
        ),
    ]
